Q_INT64_C = lambda x: x
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BlurAutoClicker.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################


from PySide6.QtCore import (QCoreApplication, QLocale,
                            QMetaObject, QRect,
                            QSize, Qt)
from PySide6.QtGui import (QFont, QIcon)
from PySide6.QtWidgets import (QAbstractSpinBox, QCheckBox, QComboBox,
                               QFrame, QGridLayout, QGroupBox, QHBoxLayout,
                               QKeySequenceEdit, QLabel, QLayout, QPushButton, QSpinBox, QTabWidget,
                               QWidget)

class Ui_BlurAutoClicker(object):
    def setupUi(self, BlurAutoClicker):
        if not BlurAutoClicker.objectName():
            BlurAutoClicker.setObjectName(u"BlurAutoClicker")
        BlurAutoClicker.setEnabled(True)
        BlurAutoClicker.resize(430, 400)
        BlurAutoClicker.setMinimumSize(QSize(430, 400))
        BlurAutoClicker.setMaximumSize(QSize(430, 400))
        icon = QIcon()
        icon.addFile(u"F:/[07] Images/[01] Purpose-Based/Blur/Profile Picture/Blur Logo 3.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        BlurAutoClicker.setWindowIcon(icon)
        BlurAutoClicker.setWindowOpacity(0.990000000000000)
        BlurAutoClicker.setAutoFillBackground(False)
        BlurAutoClicker.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        BlurAutoClicker.setIconSize(QSize(24, 24))
        BlurAutoClicker.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        BlurAutoClicker.setTabShape(QTabWidget.TabShape.Rounded)
        self.centralwidget = QWidget(BlurAutoClicker)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 411, 141))
        font = QFont()
        font.setFamilies([u"Leelawadee UI"])
        font.setPointSize(9)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.groupBox.setCheckable(False)
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 20, 391, 111))
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setToolTipDuration(-1)
        self.gridLayoutWidget.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMinimumSize(QSize(0, 0))
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(-1)
        self.label_3.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_3.addWidget(self.label_3)

        self.ClicksSpeedInputBox = QSpinBox(self.gridLayoutWidget)
        self.ClicksSpeedInputBox.setObjectName(u"ClicksSpeedInputBox")
        self.ClicksSpeedInputBox.setFont(font)
        self.ClicksSpeedInputBox.setToolTipDuration(-1)
        self.ClicksSpeedInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.ClicksSpeedInputBox.setMaximum(1999)
        self.ClicksSpeedInputBox.setValue(15)

        self.horizontalLayout_3.addWidget(self.ClicksSpeedInputBox)


        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(0, 0))
        self.label_4.setFont(font)
        self.label_4.setToolTipDuration(-1)
        self.label_4.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.label_4.setFrameShape(QFrame.Shape.NoFrame)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_4)

        self.ClickIntervalComboBox = QComboBox(self.gridLayoutWidget)
        self.ClickIntervalComboBox.addItem("")
        self.ClickIntervalComboBox.addItem("")
        self.ClickIntervalComboBox.addItem("")
        self.ClickIntervalComboBox.addItem("")
        self.ClickIntervalComboBox.setObjectName(u"ClickIntervalComboBox")
        self.ClickIntervalComboBox.setEnabled(True)
        self.ClickIntervalComboBox.setMinimumSize(QSize(100, 25))
        self.ClickIntervalComboBox.setMaximumSize(QSize(100, 25))
        self.ClickIntervalComboBox.setFont(font)
        self.ClickIntervalComboBox.setToolTipDuration(-1)
        self.ClickIntervalComboBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_4.addWidget(self.ClickIntervalComboBox)


        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_10.setStretch(0, 4)
        self.horizontalLayout_10.setStretch(1, 4)

        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.KeySequenceEdit = QKeySequenceEdit(self.gridLayoutWidget)
        self.KeySequenceEdit.setObjectName(u"KeySequenceEdit")
        self.KeySequenceEdit.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.KeySequenceEdit.setAutoFillBackground(False)
        self.KeySequenceEdit.setClearButtonEnabled(False)
        self.KeySequenceEdit.setMaximumSequenceLength(Q_INT64_C(1))

        self.horizontalLayout.addWidget(self.KeySequenceEdit)


        self.horizontalLayout_8.addLayout(self.horizontalLayout)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(11, 0, 0, 0)
        self.label_5 = QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(0, 0))
        self.label_5.setFont(font)
        self.label_5.setToolTipDuration(-1)
        self.label_5.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.label_5.setFrameShape(QFrame.Shape.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_7.addWidget(self.label_5)

        self.ActivationTypeComboBox = QComboBox(self.gridLayoutWidget)
        self.ActivationTypeComboBox.addItem("")
        self.ActivationTypeComboBox.addItem("")
        self.ActivationTypeComboBox.setObjectName(u"ActivationTypeComboBox")
        self.ActivationTypeComboBox.setEnabled(True)
        self.ActivationTypeComboBox.setMinimumSize(QSize(100, 0))
        self.ActivationTypeComboBox.setMaximumSize(QSize(100, 25))
        self.ActivationTypeComboBox.setFont(font)
        self.ActivationTypeComboBox.setToolTipDuration(-1)
        self.ActivationTypeComboBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_7.addWidget(self.ActivationTypeComboBox)


        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_8.setStretch(0, 4)
        self.horizontalLayout_8.setStretch(1, 4)

        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.label = QLabel(self.gridLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setFont(font)
        self.label.setToolTipDuration(-1)
        self.label.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_2.addWidget(self.label)

        self.MouseButtonComboBox = QComboBox(self.gridLayoutWidget)
        self.MouseButtonComboBox.addItem("")
        self.MouseButtonComboBox.addItem("")
        self.MouseButtonComboBox.addItem("")
        self.MouseButtonComboBox.setObjectName(u"MouseButtonComboBox")
        self.MouseButtonComboBox.setEnabled(True)
        self.MouseButtonComboBox.setMinimumSize(QSize(100, 25))
        self.MouseButtonComboBox.setMaximumSize(QSize(100, 25))
        self.MouseButtonComboBox.setFont(font)
        self.MouseButtonComboBox.setToolTipDuration(-1)
        self.MouseButtonComboBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_2.addWidget(self.MouseButtonComboBox)


        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(13, -1, -1, -1)
        self.ResetSettingsButton = QPushButton(self.gridLayoutWidget)
        self.ResetSettingsButton.setObjectName(u"ResetSettingsButton")
        self.ResetSettingsButton.setMinimumSize(QSize(170, 20))
        self.ResetSettingsButton.setMaximumSize(QSize(170, 25))
        self.ResetSettingsButton.setFont(font)
        self.ResetSettingsButton.setToolTipDuration(-1)
        self.ResetSettingsButton.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout_5.addWidget(self.ResetSettingsButton)


        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_9.setStretch(0, 4)
        self.horizontalLayout_9.setStretch(1, 2)

        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 160, 201, 91))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setToolTipDuration(-1)
        self.groupBox_2.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayoutWidget_2 = QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 20, 181, 61))
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setToolTipDuration(-1)
        self.gridLayoutWidget_2.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-1)
        self.label_2.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

        self.ClicksLimitInputBox = QSpinBox(self.gridLayoutWidget_2)
        self.ClicksLimitInputBox.setObjectName(u"ClicksLimitInputBox")
        self.ClicksLimitInputBox.setFont(font)
        self.ClicksLimitInputBox.setToolTipDuration(-1)
        self.ClicksLimitInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.ClicksLimitInputBox.setMaximum(9999999)
        self.ClicksLimitInputBox.setValue(0)

        self.gridLayout_2.addWidget(self.ClicksLimitInputBox, 0, 1, 1, 1)

        self.label_6 = QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setFont(font)
        self.label_6.setToolTipDuration(-1)
        self.label_6.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)

        self.SecondsLimitInputBox = QSpinBox(self.gridLayoutWidget_2)
        self.SecondsLimitInputBox.setObjectName(u"SecondsLimitInputBox")
        self.SecondsLimitInputBox.setFont(font)
        self.SecondsLimitInputBox.setToolTipDuration(-1)
        self.SecondsLimitInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.SecondsLimitInputBox.setReadOnly(False)
        self.SecondsLimitInputBox.setKeyboardTracking(True)
        self.SecondsLimitInputBox.setProperty(u"showGroupSeparator", False)
        self.SecondsLimitInputBox.setMaximum(9999999)
        self.SecondsLimitInputBox.setValue(0)

        self.gridLayout_2.addWidget(self.SecondsLimitInputBox, 1, 1, 1, 1)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 260, 411, 101))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setToolTipDuration(-1)
        self.groupBox_3.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayoutWidget_3 = QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(10, 20, 392, 71))
        self.gridLayoutWidget_3.setFont(font)
        self.gridLayoutWidget_3.setToolTipDuration(-1)
        self.gridLayoutWidget_3.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.ClickOffsetInputBox = QSpinBox(self.gridLayoutWidget_3)
        self.ClickOffsetInputBox.setObjectName(u"ClickOffsetInputBox")
        self.ClickOffsetInputBox.setFont(font)
        self.ClickOffsetInputBox.setToolTipDuration(-1)
        self.ClickOffsetInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.ClickOffsetInputBox.setMaximum(1000)
        self.ClickOffsetInputBox.setValue(5)

        self.gridLayout_3.addWidget(self.ClickOffsetInputBox, 2, 0, 1, 2)

        self.PosXInputBox = QSpinBox(self.gridLayoutWidget_3)
        self.PosXInputBox.setObjectName(u"PosXInputBox")
        self.PosXInputBox.setMaximumSize(QSize(10000, 16777215))
        self.PosXInputBox.setFont(font)
        self.PosXInputBox.setToolTipDuration(-1)
        self.PosXInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.PosXInputBox.setFrame(True)
        self.PosXInputBox.setReadOnly(False)
        self.PosXInputBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.PosXInputBox.setMaximum(999999)
        self.PosXInputBox.setValue(0)

        self.gridLayout_3.addWidget(self.PosXInputBox, 0, 0, 1, 1)

        self.EnablePositionCheckBox = QCheckBox(self.gridLayoutWidget_3)
        self.EnablePositionCheckBox.setObjectName(u"EnablePositionCheckBox")
        self.EnablePositionCheckBox.setFont(font)
        self.EnablePositionCheckBox.setToolTipDuration(-1)
        self.EnablePositionCheckBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_3.addWidget(self.EnablePositionCheckBox, 0, 3, 1, 1)

        self.ClickOffsetCheckBox = QCheckBox(self.gridLayoutWidget_3)
        self.ClickOffsetCheckBox.setObjectName(u"ClickOffsetCheckBox")
        self.ClickOffsetCheckBox.setFont(font)
        self.ClickOffsetCheckBox.setToolTipDuration(-1)
        self.ClickOffsetCheckBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_3.addWidget(self.ClickOffsetCheckBox, 2, 2, 1, 2)

        self.pushButton_3 = QPushButton(self.gridLayoutWidget_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setMinimumSize(QSize(0, 20))
        self.pushButton_3.setMaximumSize(QSize(16777215, 25))
        self.pushButton_3.setFont(font)
        self.pushButton_3.setToolTipDuration(-1)
        self.pushButton_3.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_3.addWidget(self.pushButton_3, 0, 2, 1, 1)

        self.PosYInputBox = QSpinBox(self.gridLayoutWidget_3)
        self.PosYInputBox.setObjectName(u"PosYInputBox")
        self.PosYInputBox.setMaximumSize(QSize(10000, 16777215))
        self.PosYInputBox.setFont(font)
        self.PosYInputBox.setToolTipDuration(-1)
        self.PosYInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.PosYInputBox.setFrame(True)
        self.PosYInputBox.setReadOnly(False)
        self.PosYInputBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.PosYInputBox.setMaximum(999999)
        self.PosYInputBox.setValue(0)

        self.gridLayout_3.addWidget(self.PosYInputBox, 0, 1, 1, 1)

        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(220, 160, 201, 91))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setToolTipDuration(-1)
        self.groupBox_4.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayoutWidget_4 = QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setObjectName(u"gridLayoutWidget_4")
        self.gridLayoutWidget_4.setGeometry(QRect(10, 20, 181, 61))
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setToolTipDuration(-1)
        self.gridLayoutWidget_4.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.SpeedVariationInputBox = QSpinBox(self.gridLayoutWidget_4)
        self.SpeedVariationInputBox.setObjectName(u"SpeedVariationInputBox")
        self.SpeedVariationInputBox.setMaximumSize(QSize(60, 16777215))
        self.SpeedVariationInputBox.setFont(font)
        self.SpeedVariationInputBox.setToolTipDuration(-1)
        self.SpeedVariationInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.SpeedVariationInputBox.setFrame(True)
        self.SpeedVariationInputBox.setReadOnly(False)
        self.SpeedVariationInputBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.SpeedVariationInputBox.setMaximum(200)
        self.SpeedVariationInputBox.setSingleStep(5)
        self.SpeedVariationInputBox.setValue(5)

        self.gridLayout_4.addWidget(self.SpeedVariationInputBox, 0, 1, 1, 1)

        self.label_7 = QLabel(self.gridLayoutWidget_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(500, 20))
        self.label_7.setFont(font)
        self.label_7.setToolTipDuration(-1)
        self.label_7.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMinimumSize(QSize(0, 0))
        self.label_8.setMaximumSize(QSize(500, 20))
        self.label_8.setFont(font)
        self.label_8.setToolTipDuration(-1)
        self.label_8.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)

        self.DutyCycleInputBox = QSpinBox(self.gridLayoutWidget_4)
        self.DutyCycleInputBox.setObjectName(u"DutyCycleInputBox")
        self.DutyCycleInputBox.setMaximumSize(QSize(60, 16777215))
        self.DutyCycleInputBox.setFont(font)
        self.DutyCycleInputBox.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.DutyCycleInputBox.setToolTipDuration(-1)
        self.DutyCycleInputBox.setAutoFillBackground(False)
        self.DutyCycleInputBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.DutyCycleInputBox.setWrapping(False)
        self.DutyCycleInputBox.setFrame(True)
        self.DutyCycleInputBox.setReadOnly(False)
        self.DutyCycleInputBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.DutyCycleInputBox.setAccelerated(False)
        self.DutyCycleInputBox.setMaximum(100)
        self.DutyCycleInputBox.setSingleStep(5)
        self.DutyCycleInputBox.setValue(25)

        self.gridLayout_4.addWidget(self.DutyCycleInputBox, 1, 1, 1, 1)

        self.PickingPosButton = QPushButton(self.centralwidget)
        self.PickingPosButton.setObjectName(u"PickingPosButton")
        self.PickingPosButton.setEnabled(True)
        self.PickingPosButton.setGeometry(QRect(20, 284, 195, 26))
        self.PickingPosButton.setFont(font)
        self.PickingPosButton.setFlat(True)
        self.UpdateStatusLabel = QLabel(self.centralwidget)
        self.UpdateStatusLabel.setObjectName(u"UpdateStatusLabel")
        self.UpdateStatusLabel.setGeometry(QRect(70, 370, 351, 20))
        self.UpdateStatusLabel.setMinimumSize(QSize(0, 0))
        self.UpdateStatusLabel.setMaximumSize(QSize(500, 20))
        self.UpdateStatusLabel.setFont(font)
        self.UpdateStatusLabel.setToolTipDuration(-1)
        self.UpdateStatusLabel.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.VersionLabel = QLabel(self.centralwidget)
        self.VersionLabel.setObjectName(u"VersionLabel")
        self.VersionLabel.setGeometry(QRect(10, 370, 61, 20))
        self.VersionLabel.setMinimumSize(QSize(0, 0))
        self.VersionLabel.setMaximumSize(QSize(500, 20))
        self.VersionLabel.setFont(font)
        self.VersionLabel.setToolTipDuration(-1)
        self.VersionLabel.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        BlurAutoClicker.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.PickingPosButton, self.ActivationTypeComboBox)
        QWidget.setTabOrder(self.ActivationTypeComboBox, self.ClicksSpeedInputBox)
        QWidget.setTabOrder(self.ClicksSpeedInputBox, self.ClickIntervalComboBox)
        QWidget.setTabOrder(self.ClickIntervalComboBox, self.MouseButtonComboBox)
        QWidget.setTabOrder(self.MouseButtonComboBox, self.ResetSettingsButton)
        QWidget.setTabOrder(self.ResetSettingsButton, self.ClicksLimitInputBox)
        QWidget.setTabOrder(self.ClicksLimitInputBox, self.SpeedVariationInputBox)
        QWidget.setTabOrder(self.SpeedVariationInputBox, self.SecondsLimitInputBox)
        QWidget.setTabOrder(self.SecondsLimitInputBox, self.DutyCycleInputBox)
        QWidget.setTabOrder(self.DutyCycleInputBox, self.PosXInputBox)
        QWidget.setTabOrder(self.PosXInputBox, self.PosYInputBox)
        QWidget.setTabOrder(self.PosYInputBox, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.EnablePositionCheckBox)
        QWidget.setTabOrder(self.EnablePositionCheckBox, self.ClickOffsetInputBox)
        QWidget.setTabOrder(self.ClickOffsetInputBox, self.ClickOffsetCheckBox)

        self.retranslateUi(BlurAutoClicker)

        QMetaObject.connectSlotsByName(BlurAutoClicker)
    # setupUi

    def retranslateUi(self, BlurAutoClicker):
        BlurAutoClicker.setWindowTitle(QCoreApplication.translate("BlurAutoClicker", u"BlurAutoClicker", None))
        self.groupBox.setTitle(QCoreApplication.translate("BlurAutoClicker", u"Clicker", None))
        self.label_3.setText(QCoreApplication.translate("BlurAutoClicker", u"Number of Clicks:", None))
#if QT_CONFIG(tooltip)
        self.ClicksSpeedInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p>How many clicks per period the clicker will execute.</p><p><span style=\" font-weight:700;\">Values over 250 clicks </span><span style=\" font-weight:700; color:#a1ff93;\">per second</span><span style=\" font-weight:700;\"> might </span><span style=\" font-weight:700; color:#ff8373;\">cause lag</span> depending on your computer and the software you click in, use with caution</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("BlurAutoClicker", u"Every", None))
        self.ClickIntervalComboBox.setItemText(0, QCoreApplication.translate("BlurAutoClicker", u"Second", None))
        self.ClickIntervalComboBox.setItemText(1, QCoreApplication.translate("BlurAutoClicker", u"Minute", None))
        self.ClickIntervalComboBox.setItemText(2, QCoreApplication.translate("BlurAutoClicker", u"Hour", None))
        self.ClickIntervalComboBox.setItemText(3, QCoreApplication.translate("BlurAutoClicker", u"Day", None))

#if QT_CONFIG(tooltip)
        self.ClickIntervalComboBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Decides the time span in which the Number of Clicks will be executed.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.KeySequenceEdit.setKeySequence(QCoreApplication.translate("BlurAutoClicker", u"Ctrl+K", None))
        self.label_5.setText(QCoreApplication.translate("BlurAutoClicker", u"Activation Type:", None))
        self.ActivationTypeComboBox.setItemText(0, QCoreApplication.translate("BlurAutoClicker", u"Toggle", None))
        self.ActivationTypeComboBox.setItemText(1, QCoreApplication.translate("BlurAutoClicker", u"Hold", None))

#if QT_CONFIG(tooltip)
        self.ActivationTypeComboBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p><span style=\" font-style:italic;\">Changes how the keybind affects the autoclicker.</span></p><p><span style=\" font-weight:700;\">Toggle: </span>Once the keybind is presseed, the autoclicker runs until the keybind is pressed again.</p><p><span style=\" font-weight:700;\">Hold: </span>The autoclicker is only active while the Keybind is <span style=\" font-weight:700;\">held down</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("BlurAutoClicker", u"Mouse Button:", None))
        self.MouseButtonComboBox.setItemText(0, QCoreApplication.translate("BlurAutoClicker", u"Left Click", None))
        self.MouseButtonComboBox.setItemText(1, QCoreApplication.translate("BlurAutoClicker", u"Right Click", None))
        self.MouseButtonComboBox.setItemText(2, QCoreApplication.translate("BlurAutoClicker", u"Middle Click", None))

#if QT_CONFIG(tooltip)
        self.MouseButtonComboBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"Which mouse button the Autoclicker will press.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.ResetSettingsButton.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p><span style=\" color:#ff0a0e;\">Resets all settings to default!</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.ResetSettingsButton.setText(QCoreApplication.translate("BlurAutoClicker", u"Reset Settings To Default", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("BlurAutoClicker", u"Limits", None))
        self.label_2.setText(QCoreApplication.translate("BlurAutoClicker", u"Clicks:", None))
        self.label_6.setText(QCoreApplication.translate("BlurAutoClicker", u"Seconds:", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("BlurAutoClicker", u"Position", None))
#if QT_CONFIG(tooltip)
        self.ClickOffsetInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p>Click offset will move the mouse between each click. This feature is designed to make the clicker seem more &quot;human&quot;. </p><p><span style=\" font-weight:700;\">A value between 3 and 10 is recommended</span></p><p>Please note that I have no clue if this actually does anything against the detection of this autoclicker :)</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.PosXInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"X position on screen", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.EnablePositionCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.EnablePositionCheckBox.setText(QCoreApplication.translate("BlurAutoClicker", u"Enable", None))
        self.ClickOffsetCheckBox.setText(QCoreApplication.translate("BlurAutoClicker", u"Enable Click Offset", None))
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"pick where the autoclicker should click (the mouse can not be moved while the autoclicker is active)", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setText(QCoreApplication.translate("BlurAutoClicker", u"Pick Position", None))
#if QT_CONFIG(tooltip)
        self.PosYInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"Y position on screen", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.groupBox_4.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"Tooltip", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox_4.setTitle(QCoreApplication.translate("BlurAutoClicker", u"Advanced Options", None))
#if QT_CONFIG(tooltip)
        self.SpeedVariationInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p>Speed Variation changes how fast the autoclicker clicks every click, averaging to the number of clicks set.</p><p>(50% at 10 clicks per second will fluctuate between 5 and 15 clicks per second, averaging to 10cps.)</p><p><span style=\" font-weight:700;\">A value between 10 and 90 is recommended</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.SpeedVariationInputBox.setSuffix(QCoreApplication.translate("BlurAutoClicker", u"%", None))
        self.label_7.setText(QCoreApplication.translate("BlurAutoClicker", u"Speed Variation:", None))
        self.label_8.setText(QCoreApplication.translate("BlurAutoClicker", u"Duty Cycle:", None))
#if QT_CONFIG(tooltip)
        self.DutyCycleInputBox.setToolTip(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p>Duty Cycle changes how long the mouse button is held down for each click.</p><p>(10% of 1 click per second will hold down the mouse button for 0.1 seconds before lifting it and waiting 0.9 seconds for the next click)</p><p><span style=\" font-weight:700;\">A value between 10 and 90 is recommended</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.DutyCycleInputBox.setSpecialValueText("")
        self.DutyCycleInputBox.setSuffix(QCoreApplication.translate("BlurAutoClicker", u"%", None))
        self.DutyCycleInputBox.setPrefix("")
        self.PickingPosButton.setText(QCoreApplication.translate("BlurAutoClicker", u"Picking Cursor Position in 4s", None))
        self.UpdateStatusLabel.setText(QCoreApplication.translate("BlurAutoClicker", u"<html><head/><body><p><span style=\" color:#1aff22;\">Updates Available!</span></p></body></html>", None))
        self.VersionLabel.setText(QCoreApplication.translate("BlurAutoClicker", u"v1", None))
    # retranslateUi

